/*#include "../../UTILITIES/types.h"
#include "../../UTILITIES/registers.h"
#include "../DIO DRIVER/dio.h"


uint8_t PORT_STATE = 0b01101001;
uint8_t PIN_STATE;
uint8_t READ_PIN_STATE;
uint8_t *READ_PIN = &READ_PIN_STATE;
uint8_t PIN_NUM;

int main(void)
{

for (PIN_NUM = 0 ; PIN_NUM <8 ; PIN_NUM++)
{
	DIO_PIN_INIT(PIN_NUM,PORT_A,IN);
	DIO_PIN_INIT(PIN_NUM,PORT_A,OUT);
	DIO_PIN_TOGGLE(PIN_NUM,PORT_A);
	DIO_PIN_WRITE(PIN_NUM,PORT_A,LOW);
	DIO_PIN_WRITE(PIN_NUM,PORT_A,HIGH);
	DIO_PIN_READ(PIN_NUM,PORT_A,READ_PIN);
	
	READ_PIN_STATE = 0;
	
	DIO_PIN_INIT(PIN_NUM,PORT_B,IN);
	DIO_PIN_INIT(PIN_NUM,PORT_B,OUT);
	DIO_PIN_TOGGLE(PIN_NUM,PORT_B);
	DIO_PIN_WRITE(PIN_NUM,PORT_B,LOW);
	DIO_PIN_WRITE(PIN_NUM,PORT_B,HIGH);
	DIO_PIN_READ(PIN_NUM,PORT_B,READ_PIN);
	
	READ_PIN_STATE = 0;
	
	DIO_PIN_INIT(PIN_NUM,PORT_C,IN);
	DIO_PIN_INIT(PIN_NUM,PORT_C,OUT);
	DIO_PIN_TOGGLE(PIN_NUM,PORT_C);
	DIO_PIN_WRITE(PIN_NUM,PORT_C,LOW);
	DIO_PIN_WRITE(PIN_NUM,PORT_C,HIGH);
	DIO_PIN_READ(PIN_NUM,PORT_C,READ_PIN);
	
	READ_PIN_STATE = 0;
	
	DIO_PIN_INIT(PIN_NUM,PORT_D,IN);
	DIO_PIN_INIT(PIN_NUM,PORT_D,OUT);
	DIO_PIN_TOGGLE(PIN_NUM,PORT_D);
	DIO_PIN_WRITE(PIN_NUM,PORT_D,LOW);
	DIO_PIN_WRITE(PIN_NUM,PORT_D,HIGH);
	DIO_PIN_READ(PIN_NUM,PORT_D,READ_PIN);
	

}	
	
	DIO_PORT_INIT(PORT_A,OUT);
	DIO_PORT_INIT(PORT_A,IN);
	DIO_PORT_WRITE(PORT_A,PORT_STATE);

	DIO_PORT_INIT(PORT_B,OUT);
	DIO_PORT_INIT(PORT_B,IN);
	DIO_PORT_WRITE(PORT_B,PORT_STATE);
	
	DIO_PORT_INIT(PORT_C,OUT);
	DIO_PORT_INIT(PORT_C,IN);
	DIO_PORT_WRITE(PORT_C,PORT_STATE);
	
	DIO_PORT_INIT(PORT_D,OUT);
	DIO_PORT_INIT(PORT_D,IN);
	DIO_PORT_WRITE(PORT_D,PORT_STATE);
	
}*/